### PR TITLE
fix: AI prompt breaks undo feature

### LINKED ISSUE #85: AI prompt breaks undo feature
### Summary

The CKEditor5 AI Agent plugin prevents the undo feature from working after an AI command is used. The undo button becomes unresponsive after generating AI content.

### Steps to reproduce

1. Open an editor with undo/redo buttons enabled (e.g., use the dev sample config in the 1.x branch).
2. Write some words in the editor, e.g., "test test."
3. Click the undo button.
   - Result: "test test" words are removed as expected.
4. Enter a slash command, e.g., `/test`.
5. Press enter.
6. Wait until the AI writing finishes.
7. Press the undo button.

### What is the current *bug* behavior?

The undo button is greyed out, and pressing it does nothing. The editor does not revert to the state before AI writing started.

### What is the expected *correct* behavior?

The AI-generated content should be replaced with the slash command (`/test`), restoring the state before the AI writing began. We should also prevent all history states being cleared when AI writing starts, which seems to be happening now.

### Relevant logs and/or screenshots

Untitled Video January 7, 2025 1_37 PM

### Possible fixes

The issue might involve how the AI Agent plugin integrates with CKEditor5's undo stack. Review the plugin's interaction with the editor's `model.change` or `batch` functionality to ensure undo steps are properly recorded after AI content is inserted.

### PR DESCRIPTION
**Pull request by syuzanvs**
- Preserved editor history by setting a marker when AI writing starts, allowing the undo command to revert to the state before AI content was generated.
- Updated undo and redo command handlers to check for AI writing state and prevent clearing history.
- Ensured that changes made during AI content insertion are marked as undoable, allowing users to revert to previous states.
- Improved the handling of AI-generated content to maintain a consistent user experience with the undo/redo functionality.

This commit addresses the issue where the undo button became unresponsive after generating AI content, ensuring that users can revert to the state before AI commands were executed.

Closes #85

### CODE REVIEW

File: src/aiagentservice.ts [hunk 1]
```diff
@@ -504,7 +525,12 @@ export default class AiAgentService {
 		editorContent = editorContent.replace( /<\/ai-tag>\s*<[^>]+>\s*&nbsp;\s*<\/[^>]+>/g, '' );
 		editorContent = editorContent.replace( `<ai-tag id="${ blockID }-inline">`, '' );
 		editorContent = editorContent.replace( `<ai-tag id="${ blockID }">`, '' );
-		editor.setData( editorContent );
+
+		editor.execute( 'selectAll' );
+		const viewFragment = editor.data.processor.toView( editorContent );
+		const modelFragment = editor.data.toModel( viewFragment );
+		editor.model.insertContent( modelFragment );
+		editor.editing.view.scrollToTheSelection();
```
Comment (jjroelofs) [inline src/aiagentservice.ts]: The undo/redo seems to work great now! But why did you add a scrolling behavior? I think maybe this is some experimental code belonging to another PR?

It is causing unexpected scrolling behaviors after AI writing completes:

Untitled Video January 13, 2025 6_15 PM

**Review by jjroelofs — CHANGES_REQUESTED** [review]

File: src/aiagentservice.ts (hunk 1 above)
Comment (syuzanvs) [reply src/aiagentservice.ts]: @jjroelofs I was testing something and accidentally left the code there, we don't need it. It's removed

**Review by jjroelofs — APPROVED** [review]
great!
