### PR TITLE
fix: Replace generic AI connection error with detailed API response a…

### LINKED ISSUE #55: Replace generic AI connection error with detailed API response and fallback status messages
### Summary

The error message shown when an OpenAI API key is invalid is misleading. Instead of displaying the OpenAI-provided error message (`"Incorrect API key provided..."`), the current error message suggests a connectivity issue (`"We couldn't connect to the AI. Please check your internet"`). This is incorrect and unhelpful to the user.

---

### Steps to reproduce

1. Set up CKEditor 5 with the AI plugin (AIAgent).
2. Use an invalid OpenAI API key (e.g., a placeholder or incomplete key).
3. Attempt to trigger any action requiring an OpenAI API call.
4. Observe the error message shown in the UI.

---

### What is the current *bug* behavior?

The error message displayed suggests an internet connectivity problem regardless of the actual error reason provided in the response. For example:
> "We couldn't connect to the AI. Please check your internet."

This occurs even though the OpenAI response provides a specific and actionable error message.

---

### What is the expected *correct* behavior?

The UI should prioritize displaying the specific error message returned by OpenAI. If the API response includes an error message (e.g., `"Incorrect API key provided..."`), that message should be shown to the user. Fallback messages should be used only if the API response lacks a clear error message. Additionally:
- **Status code-specific messages**: Display relevant fallback messages for common HTTP status codes (e.g., `401 Unauthorized`, `404 Not Found`).
- Avoid suggesting internet connectivity issues for errors unrelated to connectivity.

---

#### OpenAI API response (captured in Network tab):
```json
{
  "error": {
    "message": "Incorrect API key provided: sk-proj-. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
```

image

---

### Possible fixes

1. **Update error-handling logic**:
   - Extract and display the `message` field from the OpenAI API response if available.
   - Use fallback messages only when no meaningful message is returned.

2. **Add status code-dependent fallback messages**:
   - Create a library or module to manage meaningful messages for HTTP status codes. Examples:
     - `401 Unauthorized`: "Invalid API key or insufficient permissions."
     - `404 Not Found`: "The requested endpoint was not found."
     - `500 Internal Server Error`: "The AI service encountered an error. Please try again later."

3. **Proposed pseudocode**:
   ```javascript
   const httpStatusMessages = {
     401: "Unauthorized: Please check your API key or permissions.",
     404: "Not Found: The requested resource could not be located.",
     500: "Internal Server Error: Please try again later.",
   };

   function handleError(response) {
     const defaultMessage = "We couldn't connect to the AI. Please check your internet.";
     if (response.error && response.error.message) {
       return response.error.message;
     } else if (httpStatusMessages[response.status]) {
       return httpStatusMessages[response.status];
     }
     return defaultMessage;
   }
   ```

This will ensure the user receives clear, actionable error messages tailored to the situation.

### PR DESCRIPTION
**Pull request by syuzanvs**
fix: Replace generic AI connection error with detailed API response and fallback status messages

- Improved error response handling by ensuring that the error data is parsed and logged correctly when the response is not OK.
- Added more descriptive error messages for various HTTP status codes (401, 404, 500) to provide clearer feedback to users.
- Refactored the JSON validation logic to ensure robust error handling when parsing error messages.

Closes #55

### CODE REVIEW

**Review by jjroelofs — CHANGES_REQUESTED** [review]
Thanks, but there are a lot of status codes missing here, some of which are common and important in the (Open)AI ecosystem. Please either use a library or copy the list of codes and messages from a library. Whichever is easier to integrate with the CKEditor 5 translation layer:

* https://github.com/prettymuchbryce/http-status-codes
* https://github.com/prettymuchbryce/http-status-codes/blob/master/codes.json

We want to support all status codes in the above source.

File: src/aiagentservice.js [hunk 1]
```diff
@@ -308,13 +313,28 @@ export default class AiAgentService {
...
+            let status;
+            if (jsonMessage) {
+                const errorObj = JSON.parse(error === null || error === void 0 ? void 0 : error.message);
+                status = errorObj.status;
+            }
+            switch (status || (error === null || error === void 0 ? void 0 : error.name) || ((_c = error === null || error === void 0 ? void 0 : error.message) === null || _c === void 0 ? void 0 : _c.trim())) {
                 case 'ReadableStream not supported':
                     errorMessage = t('Browser does not support readable streams');
                     break;
                 case 'AiAgent: Fetch failed':
```
Comment (jjroelofs) [inline src/aiagentservice.js]: Also, please check if this case is not preventing more precise error messages from materializing. Maybe only keep this message in the default behavior? I'm not sure I didn't do a deep analysis here but please analyze this carefully

**Review by jjroelofs — CHANGES_REQUESTED** [review]
1. There are still 48 status codes missing, so the biggest problem with the PR is exactly the same problem as the last release cycle
2. I don't want to dump all 58 status code messages to aiagentservice.ts, either put them in a utility or service file, or just add the dependency to our project and integrate the messages with our translation layer some way.
3. Now that I'm thinking of it, our translation files need to be updated with translation strings for all english strings in our project, that goes for these too. You can just use Google Translate or ChatGPT for this: 
https://github.com/dxpr/ckeditor5-ai-agent/tree/1.x/lang

Don't spend too much time on doing this, just timebox half an hour to migrate the strings to the contexts.json and add the translations with ChatGPT or Google Translate.

**Review by jjroelofs — CHANGES_REQUESTED** [review]
Thanks, great work very clean now.
It seems that the JSON parsing is getting in the way of relaying error messages. When I set CKEditor config to `endpointUrl: 'https://httpstat.us/402'` I expect to see the 402 error message but instead I get:

`Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)`

I understand we need to parse JSON to check for the detailed message, but many servers do not return JSON when there is an error, so we have to account for this situation too.

**Review by jjroelofs — CHANGES_REQUESTED** [review]
## Translation bug

Thanks, great work. Everything seems to be working perfectly now.

Except for translation.

On this branch run `yarn run dll:build;yarn run dll:serve`

You can confirm Spanish translation is working by looking at the placeholder text:

Screenshot 2024-12-23 at 20 12 24

Consequently we expect the error message to be Spanish but it is actually in English:

Screenshot 2024-12-23 at 20 13 05

It does appear we account for this string in our translation file so something must be wrong in our implementation of the translation layer:


Screenshot 2024-12-23 at 20 12 48

## Translation extra work

If you pull 1.x the DLL built will default to arabic language. Please also add arabic translations and see if the notification is looking OK. I don't think its a big deal it appears on the right-hand side, but bonus points if you move it to the other side when detecting RTL language (follow CKEditor localization guidelines for this though).
